version: 0.0
os: linux
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - directory
      - file
files:
  - source: ./
    destination: /home/ubuntu/team5-server
hooks:
  AfterInstall:
    - location: /start.sh
      runas: root
