# Generated by Django 4.1.4 on 2023-01-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('95', '95'), ('100', '100'), ('105', '105'), ('110', '110'), ('115', '115'), ('120', '120'), ('125', '125'), ('130', '130'), ('135', '135'), ('140', '140'), ('145', '145'), ('150', '150'), ('155', '155'), ('160', '160'), ('165', '165'), ('170', '170'), ('175', '175'), ('180', '180'), ('185', '185'), ('190', '190'), ('195', '195'), ('200', '200'), ('205', '205'), ('210', '210'), ('215', '215'), ('220', '220'), ('225', '225'), ('230', '230'), ('235', '235'), ('240', '240'), ('245', '245'), ('250', '250'), ('255', '255'), ('260', '260'), ('265', '265'), ('270', '270'), ('275', '275'), ('280', '280'), ('285', '285'), ('290', '290'), ('295', '295'), ('300', '300'), ('305', '305'), ('310', '310'), ('315', '315'), ('320', '320'), ('325', '325'), ('330', '330'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36')], max_length=5)),
                ('purchase_price', models.IntegerField(blank=True, default=None)),
                ('selling_price', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_tag', models.CharField(choices=[('immediate', 'immediate'), ('brand', 'brand')], max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.utils.rename_imagefile_to_uuid)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productinfo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productinfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='wishes',
            field=models.ManyToManyField(through='shop.Wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
